### ISSUE TITLE
Better define how to opt-in to stdlib, jekyll-lib, and extras

### ISSUE THREAD

**Issue by epage** [cobalt-org/liquid-rust#316]
Right now
- `with_liquid` to get liquid stdlib
- `extra_filters` to get all extras

Goals
- Easy to get "libraries"
- Can opt-in to only specific features
- Ideally drop dependencies from unused features to improve build times
- Isolate breaking changes for non-std "libraries"

**Comment by Goncalerta** [comment]
I've thought on having a trait that packages all elements of a library into the `ParserBuilder`:
```rust
pub trait LiquidPackager {
    fn package_filters<B: FilterParserBuilder>(&self, B) -> B;
    
    fn package_tags<B: TagParserBuilder>(&self, B) -> B;
    
    fn package_blocks<B: BlockParserBuilder>(&self, B) -> B;
}
```
The other traits `FilterParserBuilder`, `TagParserBuilder` and `BlockParserBuilder` would be sealed traits implemented by `ParserBuilder` defined just so the functions of `LiquidPackager` can't use unexpected methods (i.e. adding a tag in `package_filters`).

# Changes on `ParserBuilder` API

1. Methods that bring whole libraries (std, jekyll, extras) into `ParserBuilder` would be removed in favor of `Packager`s for those libraries. So, `with_liquid`, `liquid`, `liquid_tags`, `liquid_blocks`, `liquid_filters`, `extra_filters`, `jekyll_filters` would all be removed (or at least deprecated).

2. The three methods `block`, `tag` and `filter` would still exist, although implemented in the aforementioned traits:
```rust
pub trait FilterParserBuilder: Sealed {
    fn filter<F>(mut self, filter: F) -> Self
      where F: Into<Box<compiler::ParseFilter>>;
}

pub trait TagParserBuilder: Sealed {
    fn tag<T>(mut self, name: &'static str, tag: T) -> Self
      where T: Into<compiler::BoxedTagParser>;
}

pub trait BlockParserBuilder: Sealed {
    fn block<B>(mut self, name: &'static str, block: B) -> Self
      where B: Into<compiler::BoxedBlockParser>;
}
```

3. A new `package` method would bring the content of a `Packager` into the `ParserBuilder`:
```rust
fn package<P: LiquidPackager>(self, package: P) -> Self 
``` 
Other methods, such as `package_filters` (only package the filters of the given `Packager`) could also be implemented.

# Name collisions

One thing to have in mind is what would happen if two `Packager`s happen to have name collisions. This may very well happen in the future between `std` and `jekyll` (see #309 and #275). 

Right know, liquid would override the existing plugin. However users could easily have the libraries swapped:
```rust
liquid::ParserBuilder::new()
    .package(StdLib)
    .package(JekyllLib)
```
versus:
```rust
liquid::ParserBuilder::new()
    .package(JekyllLib)
    .package(StdLib)
```

Well, this would inadvertently change the behavior of the `include` tag. One solution to this could be to encourage users to use a third `Package`, the `StdAndJekyllLib`, that explicitely chose the desired plugin:
```rust
liquid::ParserBuilder::new()
    .package(StdAndJekyllLib::with_jekyll_include())
```
versus
```rust
liquid::ParserBuilder::new()
    .package(StdAndJekyllLib::with_liquid_include())
```
This would not be a good solution for the general case, as more and more name collisions could start to appear.

So another option would be to have a `PackagingCollisionMode` that would define the behavior in case of a collision:
```rust
pub enum PackagingCollisionMode {
    Panic, // Two conflicting filter/tag/block names results in a `panic!`
    Override, // Discards the existing filter/tag/block in favor of the one being registered
    Skip, // Do not register the filter/tag/block if there is already one with the same name
}
```
The default would probably be `Panic`, so that unaware users would receive an error if the plugins collided. This way they could explicitely opt in to one of the modes and so be aware of which plugins they are selecting:
```rust
liquid::ParserBuilder::new()
    .package(StdLib)
    .package(JekyllLib) // `panic!`: include already defined
```
versus 
```rust
liquid::ParserBuilder::new()
    .package(StdLib)
    .package_override_duplicates(JekyllLib) // using Jekyll include, as Std was overriden
```
versus
```rust
liquid::ParserBuilder::new()
    .package(StdLib)
    .package_skip_duplicates(JekyllLib) // using Std include, as Jekyll skipped the duplicate
```

# Advantages
- Each packager may implement their own building methods (for configuring filters, packaging only a subset of the library, etc...)
- Users of liquid that create custom filters/tags/blocks may create their own packages (so they can import them all into the parser at once just like `std` and `jekyll`; currently they'd have to add them all one by one)
- Helpers for Packagers may be added in the future (for example, a wrapper that only implements the filters of a given Packager; a package merger to better handle name collision issues [see #309; #275])

For example, this wrapper struct: 
```rust
pub struct FilterPackager<T: LiquidPackager>(T);
impl LiquidPackager for FilterPackager {
    fn package_filters<B: FilterParserBuilder>(b: B) -> B {
        self.0.package_filters(b)
    }
    
    fn package_tags<B: TagParserBuilder>(b: B) -> B {
        b
    }
    
    fn package_blocks<B: BlockParserBuilder>(b: B) -> B {
        b
    }
}
```
Could be used to create a helper function that takes a Packager and returns another Packager that only packages the filters of the input. This would be an alternative to implement `package_filters` on `FilterParser`.

**Comment by epage** [comment]
Thanks for giving the time to think of and write about this.  This is an interesting approach with a lot of promise.

Some random thoughts
- Could `trait Package` just accept a `ParserBuilder` instead?  Then `trait Package` might only need one method
- Could we gain performance benefit with a `trait Package` doing bulk registration of plugins?
- Personally, I think "last writer wins" is a reasonable policy and I think aligns with how Ruby Liquid's API works

... I thought I had more but I lost it.

**Comment by Goncalerta** [comment]
> * Could `trait Package` just accept a `ParserBuilder` instead?  Then `trait Package` might only need one method

The thing is that this would allow you to implement packages that do weird stuff like:
```rust
impl LiquidPackager for MyPackage {
    fn package(&self, _b: ParserBuilder) -> ParserBuilder {
      ParserBuilder::new() // this package just returned a different parserbuilder?!
    }
}
```

I personally like the three traits/three functions structure as the user would have a specific function that they had to focus on at a time, so it would be clearer what exactly they had to do (as they could only do one thing actually). Also, I think it feels more organized to have filters, blocks, tags in separated functions, just like we have now with `liquid_tags`, `liquid_filters`, and `liquid_blocks`.


> * Could we gain performance benefit with a `trait Package` doing bulk registration of plugins?

How so? The current implementation of `block`, `tag` and `filter` just call the plugin registry, which in turn only calls `.insert` on a Hash Map. Maybe I'm missing something but I can't think of any way to register plugins that wouldn't boil down to just insert them on an Hash Map one at a time, which I believe is almost identical in performance to what we have now.

You mean calling `reserve` before inserting the plugins in the registry? Well, I guess we could expose the reserve method to allow that extra optimization.

> * Personally, I think "last writer wins" is a reasonable policy and I think aligns with how Ruby Liquid's API works

That seems good to me when inserting individual plugins. However, for packages, users could be adding two or more packages and not notice that they had collisions, resulting in unexpected behavior. 

I agree that the skip mode might be overkill. However, maybe we could have two methods, `package` (which panics) and `package_force` (which overrides the plugin). This way users could be sure that they were not overriding functionality under the hood because otherwise it would panic. If they were sure on what they were doing, they could use the force method and know they would get the last registered filter.

However, given that this would be so common that it would even happen between the two "major" libraries (Std and Jekyll), maybe you're right on having the "last writer wins" by default and warn to this behavior in the documentation.

**Comment by epage** [comment]
> The thing is that this would allow you to implement packages that do weird stuff like:

It is an interesting trade off in design to consider how much you want to protect against Murphy (mistakes) and how much you want to protect against Machiavelli (intentional abuse with ill intent).  I feel this is preventing Machiavelli and am unsure how much we should put into the design to do so.

Also, using `&mut` would be an alternative approach to make this less likely to be abused.  The downside is U suspect the entire builder would have to switch from `self` to `&mut self` which forces a `clone` on all users of the builder rather than on only the ones that need it.  Maybe that `clone` won't be so bad since it is on the construction of a Parser which happens a lot less frequently than parsing or rendering.

> Also, I think it feels more organized to have filters, blocks, tags in separated functions, just like we have now with liquid_tags, liquid_filters, and liquid_blocks.

Personally, I've dislike this part of the API.  I've felt that people would more likely want their plugins by intent than by what type of plugin it is.  Granted, in cases like `stager` where I'm using liquid toml/yaml values, we are unlikely to want tags/blocks.

To be clear on all of this, I am not making any pronouncements on what the design must be but brainstorming trade offs

**Comment by epage** [comment]
> > Could we gain performance benefit with a trait Package doing bulk registration of plugins?

> How so? ...

> You mean calling reserve before inserting the plugins in the registry? Well, I guess we could expose the reserve method to allow that extra optimization.

Something like that, yes.  A different way of getting the same result is a `filters<Iterator...>(...)`, etc.  If the iterators pass on the size hint then they will do the reserve for us and we don't have to expose that lower level mechanism.  The downside is we then need all of the plugins in a container to pass it along.  This is probably only really worth it if we can use `[]`.

**Comment by epage** [comment]
> > Personally, I think "last writer wins" is a reasonable policy and I think aligns with how Ruby Liquid's API works

> That seems good to me when inserting individual plugins. However, for packages, users could be adding two or more packages and not notice that they had collisions, resulting in unexpected behavior.

> ...

> However, given that this would be so common that it would even happen between the two "major" libraries (Std and Jekyll), maybe you're right on having the "last writer wins" by default and warn to this behavior in the documentation.

Agreed, it unfortunately turns it into a caveat emptor, especially with regards to compatibility (e.g. jekyll adding mover overlapping plugins).  As long as we don't go overboard on packages, I think it can logically make sense.  Granted, I worry I might go overboard :)

**Comment by epage** [comment]
Current thought on how to do this
- Move all filters, tags, and blocks to a `liquid-lib`
- Make it so `liquid::ParserBuilder` only exposes a `with_stdlib`.  A `stdlib` feature flag can disable this function and the entire `liquid-lib` dependency
- `liquid-lib` would have feature flags for `stdlib`, `jekyll`, and `all` to allow disabling of external dependencies

**Comment by Geobert** [comment]
For the record and avoiding conflicts, I'm looking into this :)
