### ISSUE TITLE
life-time issues when upgrading from 0.16 - 0.18

### ISSUE THREAD

**Issue by emoon** [cobalt-org/liquid-rust#344]
liquid-rust version: 0.18
rust version: 1.36
OS: Linux

Hi, I'm upgrading to 0.18 from 0.16 and I'm running into a big bunch of compile errors due to code like this

```  
   fn func(&self, sdef: &Struct, ...) { 
       let mut template_data = Object::new();
       template_data.insert("type_name".into(), Value::scalar(&sdef.name));
       let out = self.trait_impl_template.render(&template_data).unwrap();
       dest.write_all(out.as_bytes())?;
  }
```

This is used to work fine in 0.16 but in 0.18 it will complain about lifetime issues for `&sdef.name` if the code will compile again but it would result it bunch of added allocations that wasn't required before. Is it intended that this won't/shouldn't work anymore?

**Comment by epage** [comment]
Including example errors would be helpful.  My guess as to what error you are hitting is

> Value::scalar(&sdef.name)

Before, this just worked.  Now, you are probably getting an error about a `'static` lifetime is needed.

Before, we took references and allocated behind the scenes.
- [`Value::scalar` calls `Scalar::new`](https://github.com/cobalt-org/liquid-rust/blob/aaa38b047a1255956ecf35af8811d14decfc112e/liquid-value/src/values.rs#L42)
- [`Scalar::new` calls `into()`](https://github.com/cobalt-org/liquid-rust/blob/aaa38b047a1255956ecf35af8811d14decfc112e/liquid-value/src/scalar.rs#L28)
- [`into()` was implemented for `&String` and allocated](https://github.com/cobalt-org/liquid-rust/blob/aaa38b047a1255956ecf35af8811d14decfc112e/liquid-value/src/scalar.rs#L161)

Instead, we've been working to change the API to allow fewer allocations.  Scalars can now contain references.  We've not yet modified `Object` or `Array` to contain references but what you can do is implement your own [`ValueStore`](https://github.com/cobalt-org/liquid-rust/blob/master/liquid-interpreter/src/store.rs) and pass that to `render` and you can get rid of allocations by (1) using a struct rather than a HashMap and (2) not allocating for the members of the struct.  The interface is still limited, I'd like to iterate more on it.  It'd also be great if we could have a macro for deriving this for you.

**Comment by emoon** [comment]
I see. Well if it was allocating behind the scenes that wouldn't help much then no. I will just clone of all the data then. I can't send it in as `'static` as it's not static but it should be possible for `Object` to support having references to non-statics as long as the lifetimes works out (i.e the ref I send in and use for the `Object` will outlive object)
