### ISSUE TITLE
`kstring` used in public API without re-exporting the module

### ISSUE THREAD

**Issue by CJKay** [cobalt-org/liquid-rust#437]
liquid-rust uses [`kstring::KStringCow`](https://docs.rs/kstring/1.0.1/kstring/struct.KStringCow.html) in public interfaces like [`ValueView::to_kstr`](https://docs.rs/liquid/0.22.0/liquid/trait.ValueView.html#tymethod.to_kstr) but does not re-export the `kstring` module. This forces crate users to create an explicit dependency on `kstring` themselves, matching the version required by liquid-rust.

Ideally, it would make sense to try to avoid using `kstring` in public interfaces at all, but I don't know whether that's feasible or logical. An acceptable solution (and I believe the most widely-adopted solution) in the meantime is simply to add `pub extern crate kstring;` in `lib.rs`.

**Comment by epage** [comment]
Sorry for the delay on this.

> Ideally, it would make sense to try to avoid using kstring in public interfaces at all,

KString was specifically made to help with liquid though I am looking at using it in some others projects.

> An acceptable solution (and I believe the most widely-adopted solution) in the meantime is simply to add pub extern crate kstring; in lib.rs.

Not sure how much I've seen this.  Normally I see
- Re-exporting for the sake of macros being able to access items
- Newtypes to decouple crates that need to be independent (e.g. we do that for time types)

In this case, kstring is too fundamental.  We also don't need to export it for macros, even though our macros use it.  That is because its relatively easy to access without referencing it, thanks to `.into()`

I did look over at the API guidelines [but they don't say anything on the topic](https://rust-lang.github.io/api-guidelines/necessities.html#c-stable)

Personally, it feels like a bit of a wart to expose anything not directly part of the API (it irks me that macros can't access symbols from where they are declared).  If I've just missed it and there is enough of a consensus on re-export, I'm willing to go ahead.

**Comment by CJKay** [comment]
Hiya, delays aren't a problem - I'm not actively working on the project that triggered this issue at the moment.

Anyway, the problem is that right now it *is* part of the public API, through [`ValueView::to_kstr`](https://docs.rs/liquid/0.22.0/liquid/trait.ValueView.html#tymethod.to_kstr). In order to `impl ValueView` on an arbitrary external type, you need to first import the `kstring` crate.

There were previously API guidelines in this, but they were removed - there's a semi-lively discussion about this ongoing [here](https://github.com/rust-lang/api-guidelines/discussions/176). It kind of all comes down to "be sensible" which is, naturally, fairly ambiguous. In this case it's a problem I did encounter in the wild, so I would suggest it's a bug of some fashion, whether that's being unable to use a type in the public API, or misuse of the API due to misdocumentation.

**Comment by epage** [comment]
For now, I'm going ahead and embedding KString.  Expect a release soon.
